[package]
name = "storage2sql"
version = "0.1.0"
authors = ["John Newby <john@newby.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies] # <-- We added this and everything after!


[dependencies]
lazy_static = "1.4.0"
num = "0.4"
peg = "0.6.3"
regex = "1"
