[package]
name = "storage2sql"
version = "0.1.0"
authors = ["John Newby <john@newby.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies] # <-- We added this and everything after!


[dependencies]
clap = "2.33.3"
curl = "0.4.36"
env_logger = "0.8.3"
json = "0.12.4"
lazy_static = "1.4.0"
log = "0.4.0"
maplit = "1.0.2"
num = "0.4"
serde = "1.0.125"
serde_json = "1.0.64"
substring = "1.4.5"