[package]
name = "storage2sql"
version = "0.1.0"
authors = ["John Newby <john@newby.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies] # <-- We added this and everything after!


[dependencies]
chrono = "0.4"
clap = "2.33.3"
curl = "0.4.36"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
env_logger = "0.8.3"
json = "0.12.4"
lazy_static = "1.4.0"
log = "0.4.0"
num = "0.4"
postgres = "0.19.1"
regex = "1.4.5"
serde = "1.0.125"
serde_json = "1.0.64"
