[package]
name = "storage2sql"
version = "0.1.0"
authors = ["John Newby <john@newby.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies] # <-- We added this and everything after!


[dependencies]
atty = "0.2.14"
bs58 = { version = "0.4.0", features = ["check"] }
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.3"
curl = "0.4.36"
dotenv = "0.15.0"
env_logger = "0.8.3"
hex = "0.3.0"
indicatif = "0.16.0"
json = "0.12.4"
lazy_static = "1.4.0"
log = "0.4.0"
num = { version = "0.4", features = [ "serde" ] }
postgres = { version = "0.19.1", features = [ "with-chrono-0_4" ] }
regex = "1.4.5"
ron = "0.6.4"
serde = { version = "1.0.125", features = [ "derive" ] }
serde_json = "1.0.64"
spinners = "*"
